### ISSUE TITLE
categorical cavariates data 

### ISSUE THREAD

**Issue by lisongmiller** [OpenMendel/OrdinalGWAS.jl#12]
Hi Chris,

I have included 18 covariates (including 10 PC) in the null model. When categorical data in covfile is presented as numerical, like sex in (1,2). I will get error like this

┌ Warning: Optimization unsuccesful; got UserLimit
└ @ OrdinalMultinomialModels ~/.julia/packages/OrdinalMultinomialModels/fWajC/src/ordmnfit.jl:209
StatsModels.TableRegressionModel{OrdinalMultinomialModel{Int64,Float64,LogitLink},Array{Float64,2}}

If I transform categorical data in covfile is as character, like sex in ('F','M'), then no error comes out. 
So, I assume we better use character for categorical covariates?

Best,
Song

**Comment by chris-german** [comment]
Hi Song,

Although I don't know immediately why the two different codings there changed the optimization, if it succeeded with categorical string encoding, that is probably best to use. In general, I would either:
1. Code categorical variables as strings in your covfile.
2. Keep the integer encoding but read the file in as a dataframe and use `categorical!()`  or `transform` functions from DataFrames.jl on the dataframe, and use the ordinalgwas option with `ordinalgwas(formula, dataframe, geneticfile)`. 

Both of these options should lead to the same result. Let me know if you have any follow-up questions. 

Best,
Chris
