### ISSUE TITLE
ERROR: AssertionError: decompressed length mismatch

### ISSUE THREAD

**Issue by XUKEREN** [OpenMendel/OrdinalGWAS.jl#19]
Hi, 
Thank you for creating this wonderful tool! 
I encountered this error when using bgen for ordinal gwas. 

ERROR: AssertionError: decompressed length mismatch

My BGEN file was converted from VCF using qctool. I also tried using PLINK2 to convert vcf to bgen. But the ordinalgwas gave the same error when using these BGEN files converted from qctool or plink2.  

The BGEN file in your example data folder works for me.  Then I tried converting the BGEN file in your example data folder using plink2 to bgen-1.1/1.2/1.3. Same errors occur if I use the converted BGEN. 

So I think the problem might be related to the BGEN format? Any advice would be appreciated!  

Thanks,
Keren

**Comment by XUKEREN** [comment]
And the VCF file as an input file seems don't work. 
I got this error message when using the example vcf file: 
![image](https://user-images.githubusercontent.com/37352799/125818138-8e9857a4-8951-4f9a-97ae-97594f93cd5e.png)

**Comment by Hua-Zhou** [comment]
@kose-y Is this the BGEN version issue?

**Comment by kose-y** [comment]
@XUKEREN Hi, could you provide plink2 commands to reproduce this? 

> Then I tried converting the BGEN file in your example data folder using plink2 to bgen-1.1/1.2/1.3. Same errors occur if I use the converted BGEN.

**Comment by XUKEREN** [comment]
> @XUKEREN Hi, could you provide plink2 commands to reproduce this?
> 
> > Then I tried converting the BGEN file in your example data folder using plink2 to bgen-1.1/1.2/1.3. Same errors occur if I use the converted BGEN.

Sure here are the commands I used:

plink2 --bgen bgen_test.bgen ref-last  --export bgen-1.2  --out bgen_test.1.2

@kose-y

**Comment by kose-y** [comment]
Thanks. The BGEN package is not currently tested with plink-converted files, especially with the ref-last option. I will update the package to work with this situation until this weekend.

**Comment by XUKEREN** [comment]
It would be great! Thanks!

**Comment by kose-y** [comment]
Fixed it on the master branch. Please update both BGEN package and this package.

```
pkg> add https://github.com/OpenMendel/BGEN.jl
pkg> add https://github.com/OpenMendel/OrdinalGWAS.jl
```

Plink2's compression/decompression algorithm for BGEN format is not space-optimal, while the code in OrdianlGWAS.jl was assuming space-optimal compression/decompression, figuring out the decompressed size from the number of samples. Now we read the decompressed size from the corresponding field of the first variant.

**Comment by XUKEREN** [comment]
It works perfectly! Thank you so much!

**Comment by kose-y** [comment]
Also fixed VCF part: it was due to VCFTools.jl changing its VCF parser from GeneticVariant.jl to VariantCallFormat.jl. We really need to manage package versions through the `[compat]` section of `Project.toml`, rather than keeping `Manifest.toml` in repositories...
