### ISSUE TITLE
tested allele in LRT

### ISSUE THREAD

**Issue by lisongmiller** [OpenMendel/OrdinalGWAS.jl#28]
Hi there,

I was wondering in LRT test, the effect size is tested upon REF allele in bim file or the allele with minor allele frequency?
Thanks!

Best, Song

**Comment by Hua-Zhou** [comment]
It is the effect of A2 allele (usually major) specified in the Plink bim file. See <https://openmendel.github.io/SnpArrays.jl/stable/#convert-and-copyto!> for the translation of genotypes to numeric values {0, 1, 2}.
