### ISSUE TITLE
Specifying null model w/out covariates?

### ISSUE THREAD

**Issue by pmagwene** [OpenMendel/OrdinalGWAS.jl#32]
I'm interested in using OrdinalGWAS to simply fit the ordinal regression on SNPs withoutout additional covariates. What's the right way to specify the null model in this case when calling  the `ordinalgwas` function?

I tried creating a dummy "sex" covariate (with all samples set to have the same value), but unsurprisingly this raises an error if the covariate is non-variable.

**Comment by Hua-Zhou** [comment]
@pmagwene Have you tried `ordinalgwas(@formula(trait ~ sex), datadir * "covariate.txt", datadir * "hapmap3")`, where the `@formula(trait ~ sex)` specifies an intercept-only null model?

**Comment by pmagwene** [comment]
For my usecase, sex is not an appropriate covariate. 

Thinking about this a bit more, perhaps I could fit the model repeatedly, substituting a normally distributed random variable as a covariate.  Sort of a permutation based approach with a non-informative covariate...

**Comment by kose-y** [comment]
@pmagwene I hope I'm not too late to weigh in. Actually, you can do `ordinalgwas(@formula(trait ~ 0), datadir * "covariate.txt", datadir * "hapmap3")`

**Comment by kose-y** [comment]
Updated the docs. Marking as resolved.
