### ISSUE TITLE
Have row mask filter out covariate file

### ISSUE THREAD

**Issue by chris-german** [OpenMendel/OrdinalGWAS.jl#8]
Using the rowinds argument that filters the SNP data, it may be useful to also use it to filter out the covariate file so that the user does not have to create a separate covariate file that excludes missing data indices.

**Comment by Hua-Zhou** [comment]
Since v0.3.0, there is a keyword `covrowinds` that allows using selected subsamples in `covfile`. The `bedrowinds` keyword specifies selected subsamples in bed file. Check docs:
<https://openmendel.github.io/OrdinalGWAS.jl/stable/#Subsamples-1>
