### ISSUE TITLE
covariate dataset

### ISSUE THREAD

**Issue by rthapa1** [OpenMendel/OrdinalGWAS.jl#9]
Hi,

Thank you for the wonderful package. Is there any way to add population structure and kinship matrix as covariate?

Thanks

**Comment by Hua-Zhou** [comment]
You can certainly add principal components as covariates. By kinship matrix, do you mean using it as a variance component? Current package cannot handle random effects or variance component.

**Comment by rthapa1** [comment]
Yes, I want to add the kinship matrix as the random effect.

**Comment by rthapa1** [comment]
Is there a way to add a population structure matrix instead of PCA as a fixed effect?

**Comment by Hua-Zhou** [comment]
By population structure matrix, do you mean the empirical kinship matrix such as the genetic relation matrix (GRM) `GG'/S` where `G` is the column centered and scaled genotype matrix and `S` is number of SNPs? I don't see a way incorporate this matrix as fixed effects.

**Comment by rthapa1** [comment]
Thank you Zhou, it looks like MASS package doesn't allow to add random effects.
